name: Deploy .NET API to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore packages
        run: dotnet restore TrycoreEvm.sln

      - name: Build
        run: dotnet build TrycoreEvm.sln --configuration Release --no-restore

      - name: Publish API
        run: |
          dotnet publish src/TrycoreEvm.Api/TrycoreEvm.Api.csproj \
            -c Release \
            -o publish \
            --no-build

      - name: Zip publish
        run: |
          cd publish
          zip -r ../deploy.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: backend/deploy.zip
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: trycore-api
          environment_name: trycore-api-prod
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: backend/deploy.zip
        
